language: objective-c
before_script:
  - brew update
  - brew upgrade xctool
script: 
  - xctool -project 'Sample Project/Pompeu.xcodeproj' -scheme 'Pompeu' -configuration Release -sdk iphonesimulator test